# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NW Florida Detailing
email: AP@nwfldetailing.com
description: > # this means to ignore newlines until "baseurl:"
  Professional car detailing services in Northwest Florida. Pristine coastal shine 
  for your vehicle with expert interior and exterior detailing, paint correction, and ceramic coating.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nwfldetailing.com" # the base hostname & protocol for your site

# Company Information
company_name: NW Florida Detailing
address_line: Northwest Florida
telephone_number: 
fax_number: 
company_email: AP@nwfldetailing.com
google_map: 

# Social Link
facebook_link: 
twitter_link: 
linkedin_link: 
googleplus_link: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  
# Force GitHub Pages rebuild
rebuild_timestamp: 2025-01-11-07-20

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - temp-theme/
  - _site/
